import React, { useMemo, useState } from 'react';
import { AlertTriangle, CalendarDays, FileText, ShieldAlert, DoorOpen, X } from 'lucide-react';
import { tenantApi } from '../../services/api';
import { useToast } from '../../context/ToastContext';

const formatDate = (value) => value ? new Date(value).toLocaleDateString(undefined, { year: 'numeric', month: 'long', day: 'numeric' }) : '—';
const dateInput = (value) => value ? new Date(value).toISOString().slice(0, 10) : '';

export const TenantNoticesTab = ({ notices = [], loading = false, error = '', lease, onEarlyTerminationRequested = () => {} }) => {
  const toast = useToast();
  const [isRequestOpen, setIsRequestOpen] = useState(false);
  const [requestedDate, setRequestedDate] = useState('');
  const [reason, setReason] = useState('');
  const [busy, setBusy] = useState(false);
  const hasPendingRequest = useMemo(() => notices.some((notice) => notice.type === 'early_termination_request' && notice.status === 'pending'), [notices]);
  const isIndefiniteLease = lease?.leaseType === 'indefinite';
  const requestLabel = isIndefiniteLease ? 'Request to End Lease' : 'End Lease Early';

  const submitRequest = async (event) => {
    event.preventDefault(); setBusy(true);
    try {
      await tenantApi.requestEarlyLeaseEnd({ requestedMoveOutDate: requestedDate, reason });
      toast.success('Your lease end request was sent to your landlord.');
      setIsRequestOpen(false); setReason(''); setRequestedDate(''); await onEarlyTerminationRequested();
    } catch (err) { toast.error(err.message || 'Could not submit your request'); }
    finally { setBusy(false); }
  };

  return <section className="mx-auto max-w-5xl space-y-6">
    <header className="flex flex-wrap items-end justify-between gap-4">
      <div><p className="text-xs font-bold uppercase tracking-[0.2em] text-indigo-500">Resident documents</p><h1 className="mt-2 text-2xl sm:text-3xl font-extrabold font-grotesk text-slate-900 dark:text-white">Notices</h1><p className="mt-2 text-sm text-slate-500 dark:text-slate-400">Review landlord notices and your lease requests.</p></div>
      <button disabled={!lease || lease.status === 'ended' || hasPendingRequest} onClick={() => { setRequestedDate(''); setReason(''); setIsRequestOpen(true); }} className="inline-flex items-center gap-2 rounded-xl bg-indigo-600 px-4 py-2.5 text-sm font-bold text-white disabled:cursor-not-allowed disabled:opacity-50"><DoorOpen size={16} />{hasPendingRequest ? 'Lease End Request Pending' : requestLabel}</button>
    </header>
    {error && <p role="alert" className="rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-700 dark:border-rose-900 dark:bg-rose-950/30 dark:text-rose-300">{error}</p>}
    {loading ? <p className="rounded-2xl border border-slate-200 p-6 text-sm text-slate-500 dark:border-slate-800">Loading notices…</p> : notices.length === 0 ? <div className="rounded-2xl border border-slate-200 bg-white p-8 text-center dark:border-slate-800 dark:bg-[#10131F]"><ShieldAlert className="mx-auto h-9 w-9 text-slate-400" /><h2 className="mt-3 font-bold text-slate-900 dark:text-white">No notices</h2><p className="mt-1 text-sm text-slate-500 dark:text-slate-400">Landlord notices and your requests will appear here.</p></div> : notices.map((notice) => notice.type === 'early_termination_request' ? (
      <article key={notice._id || notice.id} className="rounded-2xl border border-indigo-200 bg-white p-5 dark:border-indigo-900/70 dark:bg-[#10131F] sm:p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-lg font-bold text-slate-900 dark:text-white">Lease End Request</h2><p className="mt-1 text-sm text-slate-500">{notice.property?.name || 'Property'} · {notice.unit?.label || 'Unit'}</p></div><span className="rounded-full bg-indigo-100 px-3 py-1 text-xs font-bold capitalize text-indigo-800 dark:bg-indigo-900/40 dark:text-indigo-200">{notice.status}</span></div><p className="mt-4 whitespace-pre-wrap text-sm leading-6 text-slate-700 dark:text-slate-300">{notice.reason}</p><p className="mt-4 flex items-center gap-2 text-sm text-slate-500"><CalendarDays size={16} />Requested move-out: {formatDate(notice.requestedMoveOutDate)}</p>{notice.landlordNotes && <p className="mt-4 rounded-xl bg-slate-50 p-3 text-sm text-slate-600 dark:bg-slate-900 dark:text-slate-300">Landlord note: {notice.landlordNotes}</p>}</article>
    ) : <article key={notice._id || notice.id} className="rounded-2xl border border-amber-200 bg-white p-5 dark:border-amber-900/70 dark:bg-[#10131F] sm:p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div className="flex items-start gap-3"><span className="rounded-xl bg-amber-100 p-2.5 text-amber-700 dark:bg-amber-900/30 dark:text-amber-300"><AlertTriangle className="h-5 w-5" /></span><div><h2 className="text-lg font-bold text-slate-900 dark:text-white">40-Day Eviction Notice</h2><p className="mt-1 text-sm text-slate-500">{notice.property?.name || 'Property'} · {notice.unit?.label || 'Unit'}</p></div></div><span className="rounded-full bg-amber-100 px-3 py-1 text-xs font-bold capitalize text-amber-800 dark:bg-amber-900/40 dark:text-amber-200">{notice.status || 'active'}</span></div><p className="mt-5 whitespace-pre-wrap text-sm leading-6 text-slate-700 dark:text-slate-300">{notice.reason}</p><div className="mt-5 grid gap-3 sm:grid-cols-2"><div className="flex gap-2 rounded-xl bg-slate-50 p-3 dark:bg-slate-900/70"><CalendarDays className="mt-0.5 h-4 w-4 text-indigo-500" /><div><p className="text-xs text-slate-500">Issued</p><p className="text-sm font-semibold">{formatDate(notice.issuedAt)}</p></div></div><div className="flex gap-2 rounded-xl bg-slate-50 p-3 dark:bg-slate-900/70"><CalendarDays className="mt-0.5 h-4 w-4 text-rose-500" /><div><p className="text-xs text-slate-500">Move-out date</p><p className="text-sm font-semibold">{formatDate(notice.moveOutDate)}</p></div></div></div>{notice.documentUrl && <a href={notice.documentUrl} target="_blank" rel="noreferrer" className="mt-4 inline-flex items-center gap-2 text-sm font-semibold text-indigo-600 hover:underline"><FileText className="h-4 w-4" /> View attached notice</a>}{notice.status === 'canceled' && <p className="mt-4 rounded-xl bg-slate-100 p-3 text-sm dark:bg-slate-900">This notice was canceled on {formatDate(notice.canceledAt)}.{notice.cancellationReason ? ` Reason: ${notice.cancellationReason}` : ''}</p>}{notice.status === 'overridden' && <p className="mt-4 rounded-xl bg-rose-50 p-3 text-sm text-rose-700 dark:bg-rose-950/30 dark:text-rose-300">The landlord applied an Evict Override on {formatDate(notice.overriddenAt)}.</p>}</article>)}

    {isRequestOpen && <div className="fixed inset-0 z-[60] flex items-center justify-center bg-black/60 p-4"><form onSubmit={submitRequest} role="dialog" aria-modal="true" aria-labelledby="early-end-title" className="w-full max-w-lg space-y-4 rounded-2xl bg-white p-6 dark:bg-[#10131F]"><div className="flex items-start justify-between"><div><h2 id="early-end-title" className="text-xl font-bold text-slate-900 dark:text-white">{isIndefiniteLease ? 'Request to End Lease' : 'Request to End Lease Early'}</h2><p className="mt-1 text-sm text-slate-500">This sends a request to your landlord. Your lease remains active unless your landlord approves it.</p></div><button type="button" aria-label="Close" onClick={() => setIsRequestOpen(false)} className="p-2 text-slate-500"><X size={18} /></button></div><label className="block text-sm font-semibold">Requested move-out date<input required type="date" min={dateInput(new Date(Date.now() + 86400000))} max={lease?.leaseEnd ? dateInput(lease.leaseEnd) : undefined} value={requestedDate} onChange={(event) => setRequestedDate(event.target.value)} className="mt-1 w-full rounded-xl border border-slate-300 bg-white px-3 py-2 text-slate-900 dark:border-slate-700 dark:bg-slate-900 dark:text-white" /></label><label className="block text-sm font-semibold">Reason<textarea required minLength={5} maxLength={2000} rows={4} value={reason} onChange={(event) => setReason(event.target.value)} className="mt-1 w-full rounded-xl border border-slate-300 bg-white px-3 py-2 text-slate-900 dark:border-slate-700 dark:bg-slate-900 dark:text-white" placeholder="Explain why you are requesting to end the lease" /></label><div className="flex justify-end gap-2"><button type="button" onClick={() => setIsRequestOpen(false)} className="rounded-xl border border-slate-300 px-4 py-2 text-sm text-slate-700 dark:border-slate-700 dark:text-slate-200">Cancel</button><button disabled={busy} className="rounded-xl bg-indigo-600 px-4 py-2 text-sm font-bold text-white disabled:opacity-50">{busy ? 'Submitting…' : 'Send Request'}</button></div></form></div>}
  </section>;
};
